### ISSUE TITLE
Add Codes in the language of your choice :)

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/contribute_ur_code#232]
Everyone Feel free to contribute. This issue is open to all. Just make a PR 🥳

**Comment by Manoj13-coder** [comment]
assign it to me
please

**Comment by Nitesh-thapliyal** [comment]
can i work on it ?

**Comment by KushGrandhi** [comment]
@infiniteoverflow 
please assign to me

**Comment by Ruth-ikegah** [comment]
Is this an issue that accepts different PRs from different contributors? If yes I will love to contribute

**Comment by sagunjaiswal** [comment]
@infiniteoverflow 
i want to contribute on this

**Comment by shaonakundu** [comment]
@infiniteoverflow Assign me this task I want  to contribute :)

**Comment by shaonakundu** [comment]
I will like to contribute IRIS data set or news classifier in ML according to your choice, so please allow me and assign me this task

**Comment by infiniteoverflow** [comment]
Everyone feel free to contribute. This issue is open to all :)

**Comment by Ajay0511** [comment]
I will add objection detection using YOLO algorithm.

**Comment by Keyurkariya** [comment]
I want to add tic tac toe in Golang
